### ISSUE TITLE
Error dialog:command not found

### ISSUE THREAD

**Issue by satwikkansal** [BillSkiCO/RX-Modulator#1]
When I cloned your project and then ran `sudo bash timehack` , I got the following error 
![screenshot from 2017-01-03 11-50-48](https://cloud.githubusercontent.com/assets/10217535/21601036/19a1c664-d1ab-11e6-86e8-b872728f9630.png)

**Comment by BillSkiCO** [comment]
@satwikkansal - Thanks for the issue submission. This one seems simple! You'll just have to install dialog which is used for the interactive GUI.

```bash
$ sudo apt-get update
$ sudo apt-get install dialog
```
