### ISSUE TITLE
[README update] - contributions currently will not show up

### ISSUE THREAD

**Issue by michaeltangelo** [BillSkiCO/RX-Modulator#3]
Forking will not result in contributions to show up on a user's profile. Referencing the follow guide by Github: [Github Contributions](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

Commits will only show up if 
> The commits were made in a standalone repository, not a fork.

The best way to successfully get the commits to show would be for users to create their own repo (private or public) and run the script on that repo.

**Comment by BillSkiCO** [comment]
Fixed README.md to reflect issue. Thanks for pointing this out!
