### ISSUE TITLE
[README update] - More details on how to run the script

### ISSUE THREAD

**Issue by michaeltangelo** [BillSkiCO/RX-Modulator#4]
~~1) Mac users will not be able to run the script without installing dialog first using
`brew install dialog`~~ EDIT: did not realize you updated the readme to include this already. However, I'd still suggest two sections of installation instructions (one for Linux, one for OS X)

2) Just a note: the `date` command works on Macs too, so it doesn't say much about whether the shell is BSD or GNU. Have a section in the readme that instructs users how to install gdate using
`brew install coreutils` <-- this was a painful thing to figure out

**Comment by BillSkiCO** [comment]
@michaeltangelo Awesome. Thanks for the input from the other side 🥇

**Comment by BillSkiCO** [comment]
Updated script to test if system is Darwin or Linux
